// src/pages/transactions/ConfirmDestroyTransaction.svelte
<script lang="ts">
	import type { Transaction } from "../../model/Transaction";
	import { createEventDispatcher } from "svelte";
	import ActionButton from "../../components/buttons/ActionButton.svelte";
	import Confirm from "../../components/Confirm.svelte";

	const dispatch = createEventDispatcher<{
		yes: Transaction;
		no: Transaction;
	}>();

	export let transaction: Transaction;
	export let isOpen: boolean;

	function no() {
		dispatch("no", transaction);
	}

	function yes() {
		dispatch("yes", transaction);
	}
</script>

<Confirm {isOpen} closeModal={no}>
	<!-- TODO: I18N -->
	<span slot="message"
		>Are you sure you want to delete <strong>{transaction.title ?? ""}</strong>? This cannot be
		undone.</span
	>

	<ActionButton slot="primary-action" kind="bordered-destructive" on:click={yes}>Yes</ActionButton>
	<ActionButton slot="secondary-action" kind="bordered-primary" on:click={no}>No</ActionButton>
	<!-- <ActionButton slot="cancel-action" kind="bordered-secondary" on:click={no}>Cancel</ActionButton> -->
</Confirm>

// src/pages/transactions/ConfirmDestroyTransaction.vue
<script setup lang="ts">
import type { PropType } from "vue";
import type { Transaction } from "../../model/Transaction";
import ActionButton from "../../components/buttons/ActionButton.vue";
import Confirm from "../../components/Confirm.vue";
import { toRefs } from "vue";

const emit = defineEmits(["yes", "no"]);

const props = defineProps({
	transaction: { type: Object as PropType<Transaction>, required: true },
	isOpen: { type: Boolean, required: true },
});
const { transaction } = toRefs(props);

function no() {
	emit("no", transaction.value);
}

function yes() {
	emit("yes", transaction.value);
}
</script>

<template>
	<Confirm :is-open="isOpen" :close-modal="no">
		<!-- TODO: I18N -->
		<template #message
			>Are you sure you want to delete <strong>{{ transaction.title ?? "" }}</strong
			>? This cannot be undone.</template
		>

		<template #primary-action>
			<ActionButton kind="bordered-destructive" @click="yes">Yes</ActionButton>
		</template>
		<template #secondary-action>
			<ActionButton kind="bordered-primary" @click="no">No</ActionButton>
		</template>
		<!-- <template #cancel-action>
			<ActionButton kind="bordered-secondary" @click="no">Cancel</ActionButton>
		</template> -->
	</Confirm>
</template>
