// components/transactions/TransactionMonthListItem.vue
<script setup lang="ts">
import ListItem from "../../components/ListItem.vue";
import MonthIcon from "../../icons/Month.vue";
import { computed, toRefs } from "vue";
import { transactionsByMonth } from "../../router";

const props = defineProps({
	accountId: { type: String, required: true },
	monthName: { type: String, required: true },
	count: { type: Number, required: true },
});
const { accountId, monthName, count } = toRefs(props);

const monthRoute = computed(() => {
	const month = monthName.value;
	const encodedMonth = encodeURIComponent(month);
	return transactionsByMonth(accountId.value, encodedMonth);
});
</script>

<template>
	<!-- TODO: I18N -->
	<ListItem :to="monthRoute" :title="monthName" :subtitle="`${count} transactions`">
		<template #icon>
			<MonthIcon />
		</template>
	</ListItem>
</template>

<style scoped lang="scss">
@use "styles/colors" as *;

.icon {
	margin: 4pt;
}

.list-item {
	cursor: pointer;
}
</style>

// src/pages/transactions/TransactionMonthListItem.svelte
<script lang="ts">
	import { transactionsByMonth } from "../../router";
	import ListItem from "../../components/ListItem.svelte";
	import MonthIcon from "../../icons/Month.svelte";

	export let accountId: string;
	export let monthName: string;
	export let count: number;

	$: monthRoute = transactionsByMonth(accountId, encodeURIComponent(monthName));
</script>

<!-- TODO: I18N -->
<ListItem to={monthRoute} title={monthName} subtitle={`${count} transactions`}>
	<MonthIcon slot="icon" />
</ListItem>

<style type="text/scss">
	@use "styles/colors" as *;

	.icon {
		margin: 4pt;
	}

	.list-item {
		cursor: pointer;
	}
</style>
