// src/components/TabItem.svelte
<script lang="ts">
	import type { Tab } from "../model/ui/tabs";
	import { _ } from "svelte-i18n";
	import { labelIdForTab, routeForTab } from "../model/ui/tabs";

	export let tab: Tab;
	export let isSelected: boolean = false;

	$: to = routeForTab(tab);
	$: labelId = labelIdForTab(tab);
</script>

<router-link class="item-container {isSelected ? 'selected' : ''} {$$props.class}" {to}
	>{$_(labelId)}</router-link
>

<style type="text/scss">
	@use "styles/colors" as *;

	.item-container {
		display: flex;
		align-items: center;
		min-height: 3em;
		height: 100%;
		padding: 0 1em;
		font-weight: bold;
		text-decoration: none;

		&.selected {
			border-bottom: 2pt solid color($link);
		}

		@media (hover: hover) {
			&:hover {
				background: color($gray4);
				text-decoration: none;
			}
		}
	}
</style>

// src/client/components/TabItem.vue
<script setup lang="ts">
import type { PropType } from "vue";
import type { Tab } from "../model/ui/tabs";

defineProps({
	tab: { type: String as PropType<Tab>, required: true },
	isSelected: { type: Boolean, default: false },
});
</script>

<template>
	<div class="item-container" :class="{ selected: isSelected }">
		<router-link v-if="tab === 'accounts'" to="/accounts">Accounts</router-link>
		<router-link v-else-if="tab === 'tags'" to="/tags">Tags</router-link>
	</div>
</template>

<style scoped lang="scss">
@use "styles/colors" as *;

.item-container {
	display: flex;
	align-items: center;
	min-height: 3em;
	height: 100%;

	a {
		height: 100%;
		padding: 0 1em;
		line-height: 3em;
		font-weight: bold;
		text-decoration: none;
	}

	&.selected {
		border-bottom: 2pt solid color($link);
	}

	@media (hover: hover) {
		&:hover {
			background: color($gray4);
		}
	}
}
</style>
