// src/pages/tags/ConfirmDestroyTag.svelte
<script lang="ts">
	import type { Tag } from "../../model/Tag";
	import { createEventDispatcher } from "svelte";
	import { useTransactionsStore } from "../../store";
	import ActionButton from "../../components/buttons/ActionButton.svelte";
	import Confirm from "../../components/Confirm.svelte";

	const dispatch = createEventDispatcher<{
		yes: Tag;
		no: Tag;
	}>();

	export let tag: Tag;
	export let isOpen: boolean;

	const transactions = useTransactionsStore();

	$: count = transactions.numberOfReferencesForTag(tag.id);

	function no() {
		dispatch("no", tag);
	}

	function yes() {
		dispatch("yes", tag);
	}
</script>

<Confirm {isOpen} closeModal={no}>
	<!-- TODO: I18N -->
	<span slot="message"
		>Are you sure you want to delete the tag <strong class="tag-name">{tag.name}</strong>?
		{#if count > 0}
			This tag will be removed from
			<strong>{count} transaction(s)</strong>.{/if}
		This cannot be undone.</span
	>

	<ActionButton slot="primary-action" kind="bordered-destructive" on:click={yes}>Yes</ActionButton>
	<ActionButton slot="secondary-action" kind="bordered-primary" on:click={no}>No</ActionButton>
	<!-- <ActionButton slot="cancel-action" kind="bordered-secondary" on:click={no}>Cancel</ActionButton> -->
</Confirm>

<style type="text/scss">
	.tag-name {
		&::before {
			content: "#";
		}
	}
</style>

// src/components/tags/ConfirmDestroyTag.vue
<script setup lang="ts">
import type { PropType } from "vue";
import type { Tag } from "../../model/Tag";
import ActionButton from "../buttons/ActionButton.vue";
import Confirm from "../Confirm.vue";
import { computed, toRefs } from "vue";
import { useTransactionsStore } from "../../store";

const emit = defineEmits(["yes", "no"]);

const props = defineProps({
	tag: { type: Object as PropType<Tag>, required: true },
	isOpen: { type: Boolean, required: true },
});
const { tag } = toRefs(props);

const transactions = useTransactionsStore();

const count = computed(() => transactions.numberOfReferencesForTag(tag.value.id));

function no() {
	emit("no", tag.value);
}

function yes() {
	emit("yes", tag.value);
}
</script>

<template>
	<Confirm :is-open="isOpen" :close-modal="no">
		<template #message
			>Are you sure you want to delete the tag <strong class="tag-name">{{ tag.name }}</strong
			>?<template v-if="count > 0">
				This tag will be removed from
				<strong>{{ count }} transaction(s)</strong>.</template
			>
			This cannot be undone.</template
		>

		<template #primary-action>
			<ActionButton kind="bordered-destructive" @click="yes">Yes</ActionButton>
		</template>
		<template #secondary-action>
			<ActionButton kind="bordered-primary" @click="no">No</ActionButton>
		</template>
		<!-- <template #cancel-action>
			<ActionButton kind="bordered-secondary" @click="no">Cancel</ActionButton>
		</template> -->
	</Confirm>
</template>

<style scoped lang="scss">
.tag-name {
	&::before {
		content: "#";
	}
}
</style>
