// src/components/inputs/CurrencyInput.vue
<script setup lang="ts">
import type { PropType } from "vue";
import type { Dinero } from "dinero.js";
import ActionButton from "../buttons/ActionButton.vue";
import TextField from "./TextField.vue";
import { dinero } from "dinero.js";
import { intlFormat } from "../../transformers";
import { ref, computed, toRefs, watch } from "vue";
import { USD } from "@dinero.js/currencies";
import { zeroDinero } from "../../helpers/dineroHelpers";

const emit = defineEmits(["update:modelValue"]);

const props = defineProps({
	label: { type: String as PropType<string | null>, default: null },
	modelValue: {
		type: Object as PropType<Dinero<number>>,
		default: zeroDinero,
	},
});
const { modelValue } = toRefs(props);

const isIncome = ref(false);

const zeroValue = computed<string>(() => {
	return intlFormat(zeroDinero, "standard");
});
const presentableValue = computed(() => {
	return intlFormat(modelValue.value, "standard");
});

function onInput(event: Event) {
	const input = event.target as HTMLInputElement | null;
	const rawValue = input?.value ?? "";
	updateValue(rawValue);
}

function updateValue(rawValue: string) {
	const numbersOnly = rawValue.replace(/\D/gu, "");
	let value = Number.parseInt(numbersOnly, 10);
	if (!isIncome.value) {
		value = -value;
	}
	if (Number.isNaN(value) || rawValue === "") {
		emit("update:modelValue", modelValue.value);
	} else {
		emit("update:modelValue", dinero({ amount: value, currency: USD }));
	}
}

watch(isIncome, () => {
	updateValue(presentableValue.value);
});

defineExpose({ focus });
</script>

<template>
	<label class="currency-input__container">
		<TextField
			class="currency-input"
			:label="label ?? undefined"
			:model-value="presentableValue"
			:maxlength="18"
			:placeholder="zeroValue"
			@input="onInput"
		/>
		<ActionButton class="negate" @click.prevent="isIncome = !isIncome">{{
			$t("currency.positive-or-negative")
		}}</ActionButton>
	</label>
</template>

<style scoped lang="scss">
@use "styles/colors" as *;

.currency-input {
	&__container {
		position: relative;

		.negate {
			position: absolute;
			right: 2pt;
			bottom: 19%;
			font-size: 100%;
			min-height: 1em;
			min-width: 2em;
			height: 2em;
			border-radius: 4pt;

			@media (hover: hover) {
				&:hover {
					background: color($gray4);
				}

				&:hover:disabled {
					background: none;
				}
			}
		}
	}
}
</style>

// src/components/inputs/CurrencyInput.svelte
<script lang="ts">
	import type { Dinero } from "dinero.js";
	import { _ } from "svelte-i18n";
	import { createEventDispatcher } from "svelte";
	import { dinero } from "dinero.js";
	import { intlFormat } from "../../transformers";
	import { USD } from "@dinero.js/currencies";
	import { zeroDinero } from "../../helpers/dineroHelpers";
	import ActionButton from "../buttons/ActionButton.svelte";
	import TextField from "./TextField.svelte";

	const dispatch = createEventDispatcher<{ input: Dinero<number> }>();

	export let label: string | null = null;
	export let value: Dinero<number> = zeroDinero;

	let isIncome = false;

	$: zeroValue = intlFormat(zeroDinero, "standard");
	$: presentableValue = intlFormat(value, "standard");

	function onInput(event: Event) {
		const input = event.target as HTMLInputElement | null;
		const rawValue = input?.value ?? "";
		updateValue(rawValue);
	}

	function updateValue(rawValueString: string) {
		const numbersOnly = rawValueString.replace(/\D/gu, "");
		let rawValue = Number.parseInt(numbersOnly, 10);
		if (!isIncome) {
			rawValue = -rawValue;
		}
		if (Number.isNaN(rawValue) || rawValueString === "") {
			dispatch("input", value);
		} else {
			dispatch("input", dinero({ amount: rawValue, currency: USD }));
		}
	}

	function onClick(event: Event) {
		event.preventDefault();
		isIncome = !isIncome;
	}

	$: (true || isIncome) && updateValue(presentableValue);
</script>

<label class="currency-input__container {$$props['class']}">
	<TextField
		class="currency-input"
		{label}
		value={presentableValue}
		maxlength={18}
		placeholder={zeroValue}
		on:input={onInput}
	/>
	<ActionButton class="negate" on:click={onClick}
		>{$_("currency.positive-or-negative")}</ActionButton
	>
</label>

<style type="text/scss">
	@use "styles/colors" as *;

	.currency-input {
		&__container {
			position: relative;

			.negate {
				position: absolute;
				right: 2pt;
				bottom: 19%;
				font-size: 100%;
				min-height: 1em;
				min-width: 2em;
				height: 2em;
				border-radius: 4pt;

				@media (hover: hover) {
					&:hover {
						background: color($gray4);
					}

					&:hover:disabled {
						background: none;
					}
				}
			}
		}
	}
</style>
