// src/pages/auth/Locked.vue
<script setup lang="ts">
import ActionButton from "../../components/buttons/ActionButton.vue";
import ErrorNotice from "../../components/ErrorNotice.vue";
import Footer from "../../Footer.vue";
import TextField from "../../components/inputs/TextField.vue";
import { accountsPath } from "../../router";
import { computed, nextTick, onMounted, ref } from "vue";
import { useRouter } from "vue-router";
import { useAuthStore } from "../../store/authStore";
import { useI18n } from "vue-i18n";
import { useUiStore } from "../../store";

const auth = useAuthStore();
const ui = useUiStore();
const router = useRouter();
const i18n = useI18n();

const bootstrapError = computed(() => ui.bootstrapError);
const accountId = computed(() => auth.accountId ?? "");
const password = ref("");
const isLoading = ref(false);
const loginProcessState = computed(() => auth.loginProcessState);

const accountIdField = ref<HTMLInputElement | null>(null);
const passwordField = ref<HTMLInputElement | null>(null);

onMounted(() => {
	passwordField.value?.focus();
	ui.bootstrap();
});

async function submit() {
	try {
		isLoading.value = true;

		if (!accountId.value || !password.value)
			throw new Error(i18n.t("error.form.missing-required-fields"));

		await auth.unlockVault(password.value);

		await nextTick();
		await router.replace(accountsPath());
	} catch (error) {
		ui.handleError(error);
	} finally {
		isLoading.value = false;
	}
}
</script>

<template>
	<main v-if="bootstrapError" class="content">
		<ErrorNotice :error="bootstrapError" />
		<Footer />
	</main>
	<main v-else class="content">
		<form @submit.prevent="submit">
			<p>{{ $t("locked.heading") }}</p>

			<TextField
				ref="accountIdField"
				:model-value="accountId"
				:disabled="true"
				:label="$t('login.account-id')"
				autocomplete="username"
				:shows-required="false"
				required
			/>
			<TextField
				ref="passwordField"
				v-model="password"
				type="password"
				:label="$t('login.current-passphrase')"
				placeholder="********"
				autocomplete="current-password"
				:shows-required="false"
				required
			/>
			<ActionButton type="submit" kind="bordered-primary" :disabled="isLoading">{{
				$t("locked.unlock")
			}}</ActionButton>

			<span v-if="loginProcessState === 'AUTHENTICATING'">{{
				$t("login.process.authenticating")
			}}</span>
			<span v-if="loginProcessState === 'GENERATING_KEYS'">{{
				$t("login.process.generating-keys")
			}}</span>
			<span v-if="loginProcessState === 'FETCHING_KEYS'">{{
				$t("login.process.fetching-keys")
			}}</span>
			<span v-if="loginProcessState === 'DERIVING_PKEY'">{{
				$t("login.process.deriving-pkey")
			}}</span>
		</form>
		<Footer />
	</main>
</template>

// src/pages/auth/Locked.svelte
<script lang="ts">
	import { _ } from "svelte-i18n";
	import { accountsPath } from "../../router";
	import { onMount } from "svelte";
	import { useAuthStore, useUiStore } from "../../store";
	import { useRouter } from "vue-router";
	import ActionButton from "../../components/buttons/ActionButton.svelte";
	import ErrorNotice from "../../components/ErrorNotice.svelte";
	import Footer from "../../Footer.svelte";
	import TextField from "../../components/inputs/TextField.svelte";

	const auth = useAuthStore();
	const ui = useUiStore();
	const router = useRouter();

	$: bootstrapError = ui.bootstrapError;
	$: accountId = auth.accountId ?? "";
	let password = "";
	let isLoading = false;
	$: loginProcessState = auth.loginProcessState;

	let passwordField: TextField | undefined;

	onMount(() => {
		passwordField?.focus();
		ui.bootstrap();
	});

	async function submit() {
		try {
			isLoading = true;

			if (!accountId || !password) throw new Error($_("error.form.missing-required-fields"));

			await auth.unlockVault(password);

			await router.replace(accountsPath());
		} catch (error) {
			ui.handleError(error);
		} finally {
			isLoading = false;
		}
	}
</script>

{#if bootstrapError}
	<main class="content">
		<ErrorNotice error={bootstrapError} />
		<Footer />
	</main>
{:else}
	<main class="content">
		<form on:submit|preventDefault={submit}>
			<p>{$_("locked.heading")}</p>

			<TextField
				value={accountId}
				disabled={true}
				label={$_("login.account-id")}
				autocomplete="username"
				shows-required={false}
				required
			/>
			<TextField
				bind:this={passwordField}
				bind:value={password}
				type="password"
				label={$_("login.current-passphrase")}
				placeholder="********"
				autocomplete="current-password"
				shows-required={false}
				required
			/>
			<ActionButton type="submit" kind="bordered-primary" disabled={isLoading}
				>{$_("locked.unlock")}</ActionButton
			>

			{#if loginProcessState === "AUTHENTICATING"}
				<span>{$_("login.process.reauthenticating")}</span>
			{/if}
			{#if loginProcessState === "GENERATING_KEYS"}
				<span>{$_("login.process.generating-keys")}</span>
			{/if}
			{#if loginProcessState === "FETCHING_KEYS"}
				<span>{$_("login.process.fetching-keys")}</span>
			{/if}
			{#if loginProcessState === "DERIVING_PKEY"}
				<span>{$_("login.process.deriving-pkey")}</span>
			{/if}
		</form>
		<Footer />
	</main>
{/if}
