// src/components/DiskUsage.svelte
<script lang="ts">
	import { _ } from "svelte-i18n";
	import { simplifiedByteCount } from "../transformers";
	import { useUiStore } from "../store";

	const ui = useUiStore();

	$: totalSpace = ui.totalSpace;
	$: usedSpace = ui.usedSpace;

	$: total = totalSpace !== null ? simplifiedByteCount(totalSpace) : "--";
	$: used = usedSpace !== null ? simplifiedByteCount(usedSpace) : "--";
</script>

<p class="storage">{$_("common.disk-usage", { values: { used, total } })}</p>

<style type="text/scss">
	@use "styles/colors" as *;

	.storage {
		margin: 8pt auto;
		color: color($secondary-label);
	}
</style>

// src/components/user/DiskUsage.vue
<script setup lang="ts">
import { computed } from "vue";
import { simplifiedByteCount } from "../../transformers";
import { useUiStore } from "../../store";

const ui = useUiStore();

const totalSpace = computed(() =>
	ui.totalSpace !== null ? simplifiedByteCount(ui.totalSpace) : "--"
);
const usedSpace = computed(() =>
	ui.usedSpace !== null ? simplifiedByteCount(ui.usedSpace) : "--"
);
</script>

<template>
	<p class="storage">Used {{ usedSpace }} of {{ totalSpace }}</p>
</template>

<style scoped lang="scss">
@use "styles/colors" as *;

.storage {
	margin: 8pt auto;
	color: color($secondary-label);
}
</style>
