// src/client/components/attachments/DownloadButton.vue
<script setup lang="ts">
import ActionButton from "../ActionButton.vue";
import DownloadIcon from "../../icons/Download.vue";
import { Attachment } from "../../model/Attachment";
import { computed, toRefs } from "vue";
import { downloadFileAtUrl } from "../../transport";
import { useAttachmentsStore } from "../../store";

const props = defineProps({
	file: { type: Attachment, required: true },
});
const { file } = toRefs(props);

const attachments = useAttachmentsStore();

const imgUrl = computed(() => attachments.files[file.value.id] ?? null);

function startDownload() {
	const url = imgUrl.value;
	if (url === null || !url) return;

	downloadFileAtUrl(url, file.value.title);
}
</script>

<template>
	<ActionButton kind="bordered-primary" :disabled="imgUrl === null" @click.prevent="startDownload">
		<DownloadIcon />
		<span>Download</span>
	</ActionButton>
</template>

<style scoped lang="scss">
.icon {
	margin-right: 6pt;
}
</style>

// src/components/buttons/DownloadButton.svelte
<script lang="ts">
	import type { Attachment } from "../../model/Attachment";
	import { _ } from "svelte-i18n";
	import { downloadFileAtUrl } from "../../transport";
	import { useAttachmentsStore } from "../../store";
	import ActionButton from "./ActionButton.svelte";
	import DownloadIcon from "../../icons/Download.svelte";

	export let file: Attachment;

	const attachments = useAttachmentsStore();

	$: imgUrl = attachments.files[file.id] ?? null;
	$: disabled = imgUrl === null;

	function startDownload(event: Event) {
		event.preventDefault();
		if (imgUrl === null || !imgUrl) return;

		downloadFileAtUrl(imgUrl, file.title);
	}
</script>

<ActionButton kind="bordered-primary" {disabled} on:click={startDownload}>
	<DownloadIcon class="icon" />
	<span>{$_("common.download-action")}</span>
</ActionButton>

<style type="text/scss">
	.icon {
		margin-right: 6pt;
	}
</style>
