// src/pages/accounts/AccountView.svelte
<script lang="ts">
	import type { Transaction } from "../../model/Transaction";
	import { intlFormat } from "../../transformers";
	import { isNegative as isDineroNegative } from "dinero.js";
	import { reverseChronologically } from "../../model/utility/sort";
	import { useRoute, useRouter } from "vue-router";
	import { zeroDinero } from "../../helpers/dineroHelpers";
	import AccountEdit from "./AccountEdit.svelte";
	import ActionButton from "../../components/buttons/ActionButton.svelte";
	import AddRecordListItem from "./AddRecordListItem.svelte";
	import EditIcon from "../../icons/Edit.svelte";
	import Fuse from "fuse.js";
	import List from "../../components/List.svelte";
	import Modal from "../../components/Modal.svelte";
	import SearchBar from "../../components/SearchBar.svelte";
	import TransactionCreateModal from "../transactions/TransactionCreateModal.svelte";
	import TransactionMonthListItem from "../transactions/TransactionMonthListItem.svelte";
	import TransactionListItem from "../transactions/TransactionListItem.svelte";
	import {
		months,
		transactionsForAccount,
		transactionsForAccountByMonth,
		useAccountsStore,
		watchTransactions,
	} from "../../store";

	export let accountId: string;

	const route = useRoute();
	const router = useRouter();
	const accounts = useAccountsStore();

	let isEditingAccount = false;
	let isEditingTransaction = false;

	$: account = accounts.items[accountId] ?? null;
	$: theseTransactions = Object.values($transactionsForAccount[accountId] ?? {}) //
		.sort(reverseChronologically);

	let transactionMonths: Array<[string, Array<Transaction>]>;
	$: {
		const now = new Date();
		transactionMonths = Object.entries($transactionsForAccountByMonth[accountId] ?? {}).sort(
			([monthId1], [monthId2]) => {
				// Look up the month's cached start date
				const a = $months[monthId1];
				const b = $months[monthId2];

				if (!a) console.warn(`Month ${monthId1} (a) doesn't exist in cache`);
				if (!b) console.warn(`Month ${monthId2} (b) doesn't exist in cache`);

				const aStart = a?.start ?? now;
				const bStart = b?.start ?? now;
				// Order reverse chronologically
				return bStart.getTime() - aStart.getTime();
			}
		);
	}

	$: searchClient = new Fuse(theseTransactions, { keys: ["title", "notes"] });
	$: searchQuery = (route.query["q"] ?? "").toString();
	$: filteredTransactions =
		searchQuery !== "" //
			? searchClient.search(searchQuery).map(r => r.item)
			: theseTransactions;

	$: remainingBalance = accounts.currentBalance[accountId] ?? null;
	$: isNegative = isDineroNegative(remainingBalance ?? zeroDinero);

	$: void watchTransactions(account);

	function goBack() {
		router.back();
	}

	function startCreatingTransaction() {
		isEditingTransaction = true;
	}

	function finishCreatingTransaction() {
		isEditingTransaction = false;
	}

	function startEditingAccount() {
		isEditingAccount = true;
	}

	function finishEditingAccount() {
		isEditingAccount = false;
	}
</script>

<main class="content">
	<div class="heading">
		<div class="account-title">
			<!-- TODO: I18N -->
			<h1>{account?.title || "Account"}</h1>
			<ActionButton class="edit" on:click={startEditingAccount}>
				<EditIcon />
			</ActionButton>
		</div>

		{#if remainingBalance === null}
			<p class="account-balance">--</p>
		{:else}
			<p class="account-balance {isNegative ? 'negative' : ''}">{intlFormat(remainingBalance)}</p>
		{/if}
	</div>

	<SearchBar class="search" />

	<!-- Search Results -->
	{#if searchQuery}
		<List class="transaction-months-list">
			{#each filteredTransactions as transaction (transaction.id)}
				<li class="transaction">
					<TransactionListItem {transaction} />
				</li>
			{/each}
			<li>
				<p class="footer">
					<span>{filteredTransactions.length}</span> of
					<span>{theseTransactions.length}</span>
					transaction{#if theseTransactions.length !== 1}s{/if}
				</p>
			</li>
		</List>

		<!-- Months (normal view) -->
	{:else}
		<List class="transaction-months-list">
			<li>
				<AddRecordListItem on:click={startCreatingTransaction} />
			</li>
			{#each transactionMonths as [month, monthTransactions] (month)}
				<li>
					<TransactionMonthListItem
						{accountId}
						monthName={month}
						count={monthTransactions.length}
					/>
				</li>
			{/each}
		</List>
	{/if}
</main>

{#if account}
	<TransactionCreateModal
		{account}
		isOpen={isEditingTransaction}
		closeModal={finishCreatingTransaction}
	/>
	<Modal open={isEditingAccount} closeModal={finishEditingAccount}>
		<AccountEdit {account} on:deleted={goBack} on:finished={finishEditingAccount} />
	</Modal>
{/if}

<style type="text/scss">
	@use "styles/colors" as *;

	.heading {
		display: flex;
		flex-flow: row nowrap;
		align-items: baseline;
		max-width: 36em;
		margin: 1em auto;

		> .account-title {
			display: flex;
			flex-flow: row nowrap;
			align-items: center;

			> h1 {
				margin: 0;
			}

			.edit {
				display: flex;
				flex-flow: row nowrap;
				align-items: center;
				color: color($link);
				min-height: 22pt;
				height: 22pt;
				min-width: 22pt;
				width: 22pt;
				margin-left: 8pt;

				.icon {
					height: 14pt;
				}
			}
		}

		.account-balance {
			margin: 0;
			margin-left: auto;
			text-align: right;
			font-weight: bold;
			padding-right: 0.7em;

			&.negative {
				color: color($red);
			}
		}
	}

	.search {
		max-width: 36em;
		margin: 1em auto;
	}

	.transaction-months-list {
		.footer {
			padding-top: 0.5em;
			user-select: none;
			color: color($secondary-label);
		}
	}
</style>

// src/components/accounts/AccountView.vue
<script setup lang="ts">
import type { Transaction } from "../../model/Transaction";
import AccountEdit from "./AccountEdit.vue";
import ActionButton from "../ActionButton.vue";
import AddRecordListItem from "./AddRecordListItem.vue";
import EditIcon from "../../icons/Edit.vue";
import Fuse from "fuse.js";
import List from "../List.vue";
import Modal from "../Modal.vue";
import SearchBar from "../SearchBar.vue";
import TransactionEdit from "../transactions/TransactionEdit.vue";
import TransactionListItem from "../transactions/TransactionListItem.vue";
import { dinero, isNegative as isDineroNegative } from "dinero.js";
import { intlFormat } from "../../transformers";
import { ref, computed, toRefs, watch } from "vue";
import { USD } from "@dinero.js/currencies";
import { useAccountsStore, useTransactionsStore } from "../../store";
import { useRoute, useRouter } from "vue-router";

function reverseChronologically(this: void, a: Transaction, b: Transaction): number {
	return b.createdAt.getTime() - a.createdAt.getTime();
}

const props = defineProps({
	accountId: { type: String, required: true },
});
const { accountId } = toRefs(props);

const route = useRoute();
const router = useRouter();
const accounts = useAccountsStore();
const transactions = useTransactionsStore();

const isEditingAccount = ref(false);
const isEditingTransaction = ref(false);

const account = computed(() => accounts.items[accountId.value]);
const theseTransactions = computed<Array<Transaction>>(() => {
	const allTransactions = (transactions.transactionsForAccount[accountId.value] ??
		{}) as Dictionary<Transaction>;
	return Object.values(allTransactions).sort(reverseChronologically);
});
const numberOfTransactions = computed(() => theseTransactions.value.length);

const searchClient = computed(
	() => new Fuse(theseTransactions.value, { keys: ["title", "notes"] })
);
const searchQuery = computed(() => (route.query["q"] ?? "").toString());
const filteredTransactions = computed<Array<Transaction>>(() =>
	searchQuery.value !== ""
		? searchClient.value.search(searchQuery.value).map(r => r.item)
		: theseTransactions.value
);

const remainingBalance = computed(() => accounts.currentBalance[accountId.value] ?? null);
const isNegative = computed(() =>
	isDineroNegative(remainingBalance.value ?? dinero({ amount: 0, currency: USD }))
);

watch(
	account,
	async account => {
		if (account) {
			await transactions.watchTransactions(account);
		}
	},
	{ immediate: true }
);

function goBack() {
	router.back();
}

function startCreatingTransaction() {
	isEditingTransaction.value = true;
}

function finishCreatingTransaction() {
	isEditingTransaction.value = false;
}

function startEditingAccount() {
	isEditingAccount.value = true;
}

function finishEditingAccount() {
	isEditingAccount.value = false;
}
</script>

<template>
	<main class="content">
		<div class="heading">
			<div class="account-title">
				<h1>{{ account?.title || "Account" }}</h1>
				<ActionButton class="edit" @click="startEditingAccount">
					<EditIcon />
				</ActionButton>
			</div>

			<p v-if="remainingBalance === null" class="account-balance">--</p>
			<p v-else class="account-balance" :class="{ negative: isNegative }">{{
				intlFormat(remainingBalance)
			}}</p>
		</div>

		<SearchBar class="search" />

		<List class="transactions-list">
			<li v-if="searchQuery === ''">
				<AddRecordListItem @click="startCreatingTransaction" />
			</li>
			<li v-for="transaction in filteredTransactions" :key="transaction.id" class="transaction">
				<TransactionListItem :transaction="transaction" />
			</li>
			<li>
				<p class="footer">
					<span>{{ numberOfTransactions }}</span> transaction<span v-if="numberOfTransactions !== 1"
						>s</span
					>
				</p>
			</li>
		</List>
	</main>

	<Modal v-if="account" :open="isEditingTransaction" :close-modal="finishCreatingTransaction">
		<TransactionEdit :account="account" @finished="finishCreatingTransaction" />
	</Modal>
	<Modal v-if="account" :open="isEditingAccount" :close-modal="finishEditingAccount">
		<AccountEdit :account="account" @deleted="goBack" @finished="finishEditingAccount" />
	</Modal>
</template>

<style scoped lang="scss">
@use "styles/colors" as *;

.heading {
	display: flex;
	flex-flow: row nowrap;
	align-items: baseline;
	max-width: 36em;
	margin: 1em auto;

	> .account-title {
		display: flex;
		flex-flow: row nowrap;
		align-items: center;

		> h1 {
			margin: 0;
		}

		.edit {
			display: flex;
			flex-flow: row nowrap;
			align-items: center;
			color: color($link);
			min-height: 22pt;
			height: 22pt;
			min-width: 22pt;
			width: 22pt;
			margin-left: 8pt;

			.icon {
				height: 14pt;
			}
		}
	}

	.account-balance {
		margin: 0;
		margin-left: auto;
		text-align: right;
		font-weight: bold;
		padding-right: 0.7em;

		&.negative {
			color: color($red);
		}
	}
}

.search {
	max-width: 36em;
	margin: 1em auto;
}

.transactions-list {
	.footer {
		padding-top: 0.5em;
		user-select: none;
		color: color($secondary-label);
	}
}
</style>
