// src/pages/settings/ChangePasswordForm.vue
<script setup lang="ts">
import ActionButton from "../../components/buttons/ActionButton.vue";
import TextField from "../../components/inputs/TextField.vue";
import { computed, ref } from "vue";
import { useAuthStore } from "../../store/authStore";
import { useToast } from "vue-toastification";
import { useUiStore } from "../../store";

const auth = useAuthStore();
const ui = useUiStore();
const toast = useToast();

const isLoading = ref(false);
const currentPassword = ref("");
const newPassword = ref("");
const newPasswordRepeat = ref("");

const hasChanges = computed(() => {
	return (
		currentPassword.value !== "" &&
		newPassword.value !== "" &&
		newPassword.value === newPasswordRepeat.value
	);
});

function reset() {
	currentPassword.value = "";
	newPassword.value = "";
	newPasswordRepeat.value = "";
}

async function submitNewPassword() {
	try {
		if (!currentPassword.value || !newPassword.value || !newPasswordRepeat.value) {
			throw new Error("All fields are required"); // TODO: I18N
		}
		if (newPassword.value !== newPasswordRepeat.value) {
			throw new Error("Those passwords need to match"); // TODO: I18N
		}

		isLoading.value = true;

		await auth.updatePassword(currentPassword.value, newPassword.value);
		toast.success("Your passphrase has been updated!"); // TODO: I18N
		reset();
	} catch (error) {
		ui.handleError(error);
	}
	isLoading.value = false;
}
</script>

<template>
	<form @submit.prevent="submitNewPassword">
		<!-- TODO: I18N -->
		<h3>Change Passphrase</h3>
		<TextField
			v-model="currentPassword"
			type="password"
			label="current passphrase"
			placeholder="********"
			autocomplete="current-password"
			:shows-required="false"
			required
		/>
		<TextField
			v-model="newPassword"
			type="password"
			label="new passphrase"
			placeholder="************"
			autocomplete="new-password"
			:shows-required="false"
			required
		/>
		<TextField
			v-model="newPasswordRepeat"
			type="password"
			label="new passphrase again"
			placeholder="************"
			autocomplete="new-password"
			:shows-required="false"
			required
		/>
		<div class="buttons">
			<ActionButton type="submit" kind="bordered-primary" :disabled="!hasChanges || isLoading"
				>Change passphrase</ActionButton
			>
			<ActionButton v-show="hasChanges" kind="bordered" :disabled="isLoading" @click.prevent="reset"
				>Reset</ActionButton
			>
		</div>
	</form>
</template>

<style scoped lang="scss">
.buttons {
	display: flex;
	flex-flow: row nowrap;

	:not(:last-child) {
		margin-right: 8pt;
	}
}
</style>

// src/pages/settings/ChangePasswordForm.svelte
<script lang="ts">
	import { _ } from "svelte-i18n";
	import { useAuthStore } from "../../store/authStore";
	import { useToast } from "vue-toastification";
	import { useUiStore } from "../../store";
	import ActionButton from "../../components/buttons/ActionButton.svelte";
	import TextField from "../../components/inputs/TextField.svelte";

	const auth = useAuthStore();
	const ui = useUiStore();
	const toast = useToast();

	let isLoading = false;
	let currentPassword = "";
	let newPassword = "";
	let newPasswordRepeat = "";

	$: hasChanges = currentPassword !== "" && newPassword !== "" && newPassword === newPasswordRepeat;

	function reset(event?: Event) {
		event?.preventDefault();
		currentPassword = "";
		newPassword = "";
		newPasswordRepeat = "";
	}

	async function submitNewPassword() {
		try {
			if (!currentPassword || !newPassword || !newPasswordRepeat) {
				throw new Error($_("error.form.missing-required-fields"));
			}
			if (newPassword !== newPasswordRepeat) {
				throw new Error($_("error.form.password-mismatch"));
			}

			isLoading = true;

			await auth.updatePassword(currentPassword, newPassword);
			toast.success("Your passphrase has been updated!"); // TODO: I18N
			reset();
		} catch (error) {
			ui.handleError(error);
		}
		isLoading = false;
	}
</script>

<form on:submit|preventDefault={submitNewPassword}>
	<!-- TODO: I18N -->
	<h3>Change Passphrase</h3>
	<TextField
		value={currentPassword}
		on:input={e => (currentPassword = e.detail)}
		type="password"
		label="current passphrase"
		placeholder="********"
		autocomplete="current-password"
		showsRequired={false}
		required
	/>
	<TextField
		value={newPassword}
		on:input={e => (newPassword = e.detail)}
		type="password"
		label="new passphrase"
		placeholder="************"
		autocomplete="new-password"
		showsRequired={false}
		required
	/>
	<TextField
		value={newPasswordRepeat}
		on:input={e => (newPasswordRepeat = e.detail)}
		type="password"
		label="new passphrase again"
		placeholder="************"
		autocomplete="new-password"
		showsRequired={false}
		required
	/>
	<div class="buttons">
		<ActionButton type="submit" kind="bordered-primary" disabled={!hasChanges || isLoading}
			>Change passphrase</ActionButton
		>
		{#if hasChanges}
			<ActionButton kind="bordered" disabled={isLoading} on:click={reset}>Reset</ActionButton>
		{/if}
	</div>
</form>

<style type="text/scss">
	.buttons {
		display: flex;
		flex-flow: row nowrap;

		:not(:last-child) {
			margin-right: 8pt;
		}
	}
</style>
