// src/pages/settings/ConfirmDeleteEverything.vue
<script setup lang="ts">
import ActionButton from "../../components/buttons/ActionButton.vue";
import Confirm from "../../components/Confirm.vue";

const emit = defineEmits(["yes", "no"]);

defineProps({
	isOpen: { type: Boolean, required: true },
});

function no() {
	emit("no");
}

function yes() {
	emit("yes");
}
</script>

<template>
	<Confirm :is-open="isOpen" :close-modal="no">
		<template #message
			>Are you sure you want to delete <strong>all of your data</strong>? This cannot be
			undone.</template
		>

		<template #primary-action>
			<ActionButton kind="bordered-destructive" @click="yes">Yes</ActionButton>
		</template>
		<template #secondary-action>
			<ActionButton kind="bordered-primary" @click="no">No</ActionButton>
		</template>
	</Confirm>
</template>

// src/pages/settings/ConfirmDeleteEverything.svelte
<script lang="ts">
	import { createEventDispatcher } from "svelte";
	import ActionButton from "../../components/buttons/ActionButton.svelte";
	import Confirm from "../../components/Confirm.svelte";

	const dispatch = createEventDispatcher<{
		yes: void;
		no: void;
	}>();

	export let isOpen: boolean;

	function no() {
		dispatch("no");
	}

	function yes() {
		dispatch("yes");
	}
</script>

<Confirm {isOpen} closeModal={no}>
	<!-- TODO: I18N -->
	<span slot="message"
		>Are you sure you want to delete <strong>all of your data</strong>? This cannot be undone.</span
	>

	<ActionButton slot="primary-action" kind="bordered-destructive" on:click={yes}>Yes</ActionButton>
	<ActionButton slot="secondary-action" kind="bordered-primary" on:click={no}>No</ActionButton>
</Confirm>
