// src/client/components/settings/ImportProcessModal.vue
<script setup lang="ts">
import type { PropType } from "vue";
import type { DatabaseSchema } from "../../model/DatabaseSchema";
import type JSZip from "jszip";
import ActionButton from "../ActionButton.vue";
import AccountListItem from "../accounts/AccountListItem.vue";
import Checkmark from "../../icons/Checkmark.vue";
import List from "../List.vue";
import Modal from "../Modal.vue";
import { computed, ref, reactive, toRefs, watch, nextTick } from "vue";
import { Account } from "../../model/Account";
import { useToast } from "vue-toastification";
import {
	useAccountsStore,
	useAttachmentsStore,
	useLocationsStore,
	useTagsStore,
	useUiStore,
} from "../../store";

const emit = defineEmits(["finished"]);

const props = defineProps({
	fileName: { type: String, default: "" },
	zip: { type: Object as PropType<JSZip | null>, default: null },
	db: { type: Object as PropType<DatabaseSchema | null>, default: null },
});
const { db, zip, fileName } = toRefs(props);

const accounts = useAccountsStore();
const attachments = useAttachmentsStore();
const locations = useLocationsStore();
const tags = useTagsStore();
const ui = useUiStore();
const toast = useToast();

const accountIdsToImport = reactive(new Set<string>());
const numberOfAttachmentsToImport = computed(() => db.value?.attachments?.length ?? 0);
const numberOfLocationsToImport = computed(() => db.value?.locations?.length ?? 0);
const numberOfTagsToImport = computed(() => db.value?.tags?.length ?? 0);
const isImporting = ref(false);
const importProgress = ref(1);
const importProgressPercent = computed(() =>
	Intl.NumberFormat(undefined, { style: "percent" }).format(importProgress.value)
);

const hasDb = computed(() => db.value !== null);
const storedAccounts = computed(() => accounts.allAccounts);
const importedAccounts = computed(() =>
	(db.value?.accounts ?? []).map(acct => new Account(acct.id, acct))
);
const duplicateAccounts = computed(() =>
	importedAccounts.value.filter(a1 => storedAccounts.value.some(a2 => a2.id === a1.id))
);
const newAccounts = computed(() =>
	importedAccounts.value.filter(a1 => !storedAccounts.value.some(a2 => a2.id === a1.id))
);
const transactionCounts = computed<Dictionary<number>>(() => {
	const result: Dictionary<number> = {};
	if (!db.value) return result;

	const accounts = db.value?.accounts ?? [];
	for (const a of accounts) {
		result[a.id] = (a.transactions ?? []).length;
	}

	return result;
});

watch(importedAccounts, importedAccounts => {
	if (hasDb.value && importedAccounts.length === 0) {
		toast.info(`${fileName.value || "That file"} contains no financial data.`);
		forgetDb();
	}
});

function toggleAccount(account: Account) {
	if (isImporting.value) return; // Don't modify import while we're importing

	if (accountIdsToImport.has(account.id)) {
		accountIdsToImport.delete(account.id);
	} else {
		accountIdsToImport.add(account.id);
	}
}

function forgetDb() {
	if (!isImporting.value) {
		emit("finished");
	}
}

// TODO: Analyze the consequenses of this import. Will this overwrite some entries, and add other ones?
async function beginImport() {
	if (!db.value) return;
	isImporting.value = true;
	importProgress.value = 0;

	try {
		let total = accountIdsToImport.size || 1;
		let finished = 0;

		for (const accountId of accountIdsToImport) {
			const accountToImport = db.value.accounts?.find(a => a.id === accountId);
			if (!accountToImport) continue;
			await accounts.importAccount(accountToImport);

			importProgress.value = finished / total;
			await nextTick();
		}

		await locations.importLocations(db.value.locations ?? []);
		await tags.importTags(db.value.tags ?? []);
		await attachments.importAttachments(db.value.attachments ?? [], zip.value);

		toast.success("Imported all the things!");
		emit("finished");
	} catch (error: unknown) {
		ui.handleError(error);
	}

	importProgress.value = 1;
	await nextTick();
	isImporting.value = false;
}
</script>

<template>
	<Modal :open="hasDb" :close-modal="forgetDb">
		<h1>Select Accounts from &quot;{{ fileName }}&quot;</h1>

		<div v-if="newAccounts.length > 0">
			<h4>New Accounts</h4>
			<List>
				<li v-for="account in newAccounts" :key="account.id" class="importable">
					<AccountListItem
						class="account"
						:account="account"
						:link="false"
						:count="transactionCounts[account.id] ?? 0"
						@click.prevent="() => toggleAccount(account)"
					/>
					<Checkmark v-if="accountIdsToImport.has(account.id)" />
				</li>
			</List>
		</div>

		<div v-if="duplicateAccounts.length > 0">
			<h4>Duplicate Accounts</h4>
			<p
				>These entries seem to match an account you already have. Would you like to overwrite the
				account and transactions we have stored with what you gave us here?</p
			>
			<List>
				<li v-for="account in duplicateAccounts" :key="account.id" class="importable">
					<AccountListItem
						class="account"
						:account="account"
						:link="false"
						:count="transactionCounts[account.id] ?? 0"
						@click.prevent="() => toggleAccount(account)"
					/>
					<Checkmark v-if="accountIdsToImport.has(account.id)" />
				</li>
			</List>
		</div>

		<div>
			<h4>Everything Else</h4>
			<List>
				<li class="importable">{{ numberOfLocationsToImport }} locations <Checkmark /></li>
				<li class="importable">{{ numberOfTagsToImport }} tags <Checkmark /></li>
				<li class="importable">{{ numberOfAttachmentsToImport }} attachments <Checkmark /></li>
			</List>
		</div>

		<div class="buttons">
			<ActionButton
				class="continue"
				kind="bordered-primary"
				:disabled="isImporting || accountIdsToImport.size === 0"
				@click.prevent="beginImport"
			>
				<span v-if="isImporting">Importing... ({{ importProgressPercent }})</span>
				<span v-else>Begin Import</span>
			</ActionButton>
		</div>
	</Modal>
</template>

<style scoped lang="scss">
@use "styles/colors" as *;

.importable {
	display: flex;
	flex-flow: row nowrap;
	align-items: center;

	.account {
		width: 100%;
	}

	.icon {
		margin-left: 8pt;
	}
}

.buttons {
	display: flex;
	flex-flow: row wrap;

	:not(:last-child) {
		margin-right: 8pt;
	}

	.continue {
		margin-left: auto;
	}
}
</style>

// src/pages/settings/ImportProcessModal.svelte
<script lang="ts">
	import type { Account } from "../../model/Account";
	import type { DatabaseSchema } from "../../model/DatabaseSchema";
	import type { Entry } from "@zip.js/zip.js";
	import { account as newAccount } from "../../model/Account";
	import { createEventDispatcher, tick } from "svelte";
	import { toast } from "@zerodevx/svelte-toast";
	import ActionButton from "../../components/buttons/ActionButton.svelte";
	import AccountListItem from "../../pages/accounts/AccountListItem.svelte";
	import Checkmark from "../../icons/Checkmark.svelte";
	import List from "../../components/List.svelte";
	import Modal from "../../components/Modal.svelte";
	import {
		useAccountsStore,
		useAttachmentsStore,
		useLocationsStore,
		useTagsStore,
		useUiStore,
	} from "../../store";

	const dispatch = createEventDispatcher<{
		finished: void;
	}>();

	export let fileName: string = "";
	export let zip: Array<Entry> | null = null;
	export let db: DatabaseSchema | null = null;

	const accounts = useAccountsStore();
	const attachments = useAttachmentsStore();
	const locations = useLocationsStore();
	const tags = useTagsStore();
	const ui = useUiStore();

	let accountIdsToImport = new Set<string>();
	$: numberOfAttachmentsToImport = db?.attachments?.length ?? 0;
	$: numberOfLocationsToImport = db?.locations?.length ?? 0;
	$: numberOfTagsToImport = db?.tags?.length ?? 0;

	let isImporting = false;
	let itemsImported = 0;

	function numberOfTransactionsToImport(): number {
		let count = 0;
		accountIdsToImport.forEach(a => {
			count += transactionCounts.value[a] ?? 0;
		});
		return count;
	}
	$: totalItemsToImport =
		numberOfTransactionsToImport() +
		numberOfTagsToImport +
		numberOfLocationsToImport +
		numberOfAttachmentsToImport +
		accountIdsToImport.size;

	$: importProgress =
		totalItemsToImport === 0 //
			? 1
			: itemsImported / totalItemsToImport;
	$: importProgressPercent = Intl.NumberFormat(undefined, { style: "percent" }) //
		.format(importProgress);

	$: hasDb = db !== null;
	$: storedAccounts = accounts.allAccounts;
	$: importedAccounts = (db?.accounts ?? []) //
		.map(acct => newAccount({ ...acct, notes: acct.notes ?? null }));

	$: duplicateAccounts = importedAccounts //
		.filter(a1 => storedAccounts.some(a2 => a2.id === a1.id));

	$: newAccounts = importedAccounts //
		.filter(a1 => !storedAccounts.some(a2 => a2.id === a1.id));

	let transactionCounts: Record<string, number> = {};
	$: (db?.accounts ?? []).forEach(a => {
		transactionCounts[a.id] = (a.transactions ?? []).length;
	});

	$: if (hasDb && importedAccounts.length === 0) {
		toast.push(`${fileName || "That file"} contains no financial data.`); // TODO: I18N
		forgetDb();
	}

	function toggleAccount(event: Event, account: Account) {
		event.preventDefault();
		if (isImporting) return; // Don't modify import while we're importing

		if (accountIdsToImport.has(account.id)) {
			accountIdsToImport.delete(account.id);
		} else {
			accountIdsToImport.add(account.id);
		}
		accountIdsToImport = accountIdsToImport; // mark for reaction
	}

	function forgetDb() {
		if (!isImporting) {
			dispatch("finished");
		}
	}

	// TODO: Analyze the consequenses of this import. Will this overwrite some entries, and add other ones?
	async function beginImport(event: Event) {
		event.preventDefault();
		if (!db) return;
		isImporting = true;
		itemsImported = 0;

		try {
			for (const accountId of accountIdsToImport) {
				const accountToImport = db.accounts?.find(a => a.id === accountId);
				if (!accountToImport) continue;
				await accounts.importAccount(accountToImport);

				itemsImported += transactionCounts.value[accountToImport.id] ?? 0;
				itemsImported += 1;
				await tick();
			}

			await locations.importLocations(db.locations ?? []);
			itemsImported += numberOfLocationsToImport;
			await tick();

			await tags.importTags(db.tags ?? []);
			itemsImported += numberOfTagsToImport;
			await tick();

			await attachments.importAttachments(db.attachments ?? [], zip);
			itemsImported += numberOfAttachmentsToImport;
			await tick();

			toast.push("Imported all the things!", { classes: ["toast-success"] }); // TODO: I18N
			dispatch("finished");
		} catch (error) {
			ui.handleError(error);
		}

		isImporting = false;
	}
</script>

<Modal open={hasDb} closeModal={forgetDb}>
	<!-- TODO: I18N -->
	<h1>Select Accounts from &quot;{fileName}&quot;</h1>

	{#if newAccounts.length > 0}
		<div>
			<h4>New Accounts</h4>
			<List>
				{#each newAccounts as account (account.id)}
					<li class="importable">
						<AccountListItem
							class="account"
							{account}
							link={false}
							count={transactionCounts[account.id] ?? 0}
							on:click={e => toggleAccount(e, account)}
						/>
						{#if accountIdsToImport.has(account.id)}
							<Checkmark />
						{/if}
					</li>
				{/each}
			</List>
		</div>
	{/if}

	{#if duplicateAccounts.length > 0}
		<div>
			<h4>Duplicate Accounts</h4>
			<p
				>These entries seem to match an account you already have. Would you like to overwrite the
				account and transactions we have stored with what you gave us here?</p
			>
			<List>
				{#each duplicateAccounts as account (account.id)}
					<li class="importable">
						<AccountListItem
							class="account"
							{account}
							link={false}
							count={transactionCounts[account.id] ?? 0}
							on:click={e => toggleAccount(e, account)}
						/>
						{#if accountIdsToImport.has(account.id)}
							<Checkmark />
						{/if}
					</li>
				{/each}
			</List>
		</div>
	{/if}

	<div>
		<h4>Everything Else</h4>
		<List>
			<li class="importable">{numberOfLocationsToImport} locations <Checkmark /></li>
			<li class="importable">{numberOfTagsToImport} tags <Checkmark /></li>
			<li class="importable">{numberOfAttachmentsToImport} attachments <Checkmark /></li>
		</List>
	</div>

	<div class="buttons">
		<ActionButton
			class="continue"
			kind="bordered-primary"
			disabled={isImporting || accountIdsToImport.size === 0}
			on:click={beginImport}
		>
			{#if isImporting}
				<span>Importing... ({importProgressPercent})</span>
			{:else}
				<span>Begin Import</span>
			{/if}
		</ActionButton>
	</div>
</Modal>

<style type="text/scss">
	@use "styles/colors" as *;

	.importable {
		display: flex;
		flex-flow: row nowrap;
		align-items: center;

		.account {
			width: 100%;
		}

		.icon {
			margin-left: 8pt;
		}
	}

	.buttons {
		display: flex;
		flex-flow: row wrap;

		:not(:last-child) {
			margin-right: 8pt;
		}

		.continue {
			margin-left: auto;
		}
	}
</style>
