// src/pages/attachments/ConfirmDestroyFile.svelte
<script lang="ts">
	import type { Attachment } from "../../model/Attachment";
	import { createEventDispatcher } from "svelte";
	import ActionButton from "../../components/buttons/ActionButton.svelte";
	import Confirm from "../../components/Confirm.svelte";

	const dispatch = createEventDispatcher<{
		yes: Attachment;
		no: Attachment;
	}>();

	export let file: Attachment | null = null;
	export let isOpen: boolean;

	function no() {
		if (file) {
			dispatch("no", file);
		}
	}

	function yes() {
		if (file) {
			dispatch("yes", file);
		}
	}
</script>

<Confirm {isOpen} closeModal={no}>
	<!-- TODO: I18N -->
	<span slot="message"
		>Are you sure you want to delete {#if file}<strong>{file.title}</strong>{:else}<span
				>this file</span
			>{/if}? This cannot be undone.</span
	>

	<ActionButton slot="primary-action" kind="bordered-destructive" on:click={yes}>Yes</ActionButton>

	<ActionButton slot="secondary-action" kind="bordered-primary" on:click={no}>No</ActionButton>
</Confirm>

// src/pages/attachments/ConfirmDestroyFile.vue
<script setup lang="ts">
import type { PropType } from "vue";
import type { Attachment } from "../../model/Attachment";
import ActionButton from "../../components/buttons/ActionButton.vue";
import Confirm from "../../components/Confirm.vue";
import { toRefs } from "vue";

const emit = defineEmits(["yes", "no"]);

const props = defineProps({
	file: { type: Object as PropType<Attachment | null>, default: null },
	isOpen: { type: Boolean, required: true },
});
const { file } = toRefs(props);

function no() {
	if (file.value) {
		emit("no", file.value);
	}
}

function yes() {
	if (file.value) {
		emit("yes", file.value);
	}
}
</script>

<template>
	<Confirm :is-open="isOpen" :close-modal="no">
		<template #message
			>Are you sure you want to delete <strong v-if="file">{{ file.title }}</strong
			><span v-else>this file</span>? This cannot be undone.</template
		>

		<template #primary-action>
			<ActionButton kind="bordered-destructive" @click="yes">Yes</ActionButton>
		</template>
		<template #secondary-action>
			<ActionButton kind="bordered-primary" @click="no">No</ActionButton>
		</template>
	</Confirm>
</template>
