// src/pages/attachments/FileListItem.vue
<script setup lang="ts">
import type { Attachment } from "../../model/Attachment";
import FileView from "./FileView.vue";
import ListItem from "../../components/ListItem.vue";
import Modal from "../../components/Modal.vue";
import { ref, computed, toRefs } from "vue";
import { toTimestamp } from "../../transformers";
import { useAttachmentsStore } from "../../store";

const props = defineProps({
	fileId: { type: String, required: true },
});
const { fileId } = toRefs(props);

const emit = defineEmits(["delete", "delete-reference", "click"]);

const attachments = useAttachmentsStore();

const file = computed(() => attachments.items[fileId.value]);
const title = computed<string>(() => file.value?.title ?? fileId.value);
const subtitle = computed<string>(() => {
	if (!file.value) return "Broken reference";

	const timestamp = toTimestamp(file.value.createdAt);

	if (file.value.notes === null || !file.value.notes) {
		return timestamp;
	}
	return `${file.value.notes} - ${timestamp}`;
});

const isModalOpen = ref(false);

function presentImageModal(event: Event) {
	emit("click", event);
	isModalOpen.value = true;
}

function closeModal() {
	isModalOpen.value = false;
}

function askToDelete(file: Attachment) {
	emit("delete", file);
}

function askToDeleteReference() {
	emit("delete-reference", fileId.value);
}
</script>

<template>
	<ListItem :title="title" :subtitle="subtitle" to="" @click.prevent="presentImageModal" />
	<Modal :open="isModalOpen && !!file" :close-modal="closeModal">
		<FileView :file="file" @delete="askToDelete" @delete-reference="askToDeleteReference" />
	</Modal>
</template>

// src/pages/attachments/FileListItem.svelte
<script lang="ts">
	import type { Attachment } from "../../model/Attachment";
	import { createEventDispatcher } from "svelte";
	import { toTimestamp } from "../../transformers";
	import { useAttachmentsStore } from "../../store";
	import FileView from "./FileView.svelte";
	import ListItem from "../../components/ListItem.svelte";
	import Modal from "../../components/Modal.svelte";

	const dispatch = createEventDispatcher<{
		delete: Attachment;
		"delete-reference": string;
		click: Event;
	}>();

	export let fileId: string;

	const attachments = useAttachmentsStore();

	$: file = attachments.items[fileId];
	$: title = file?.title ?? fileId;
	$: timestamp = toTimestamp(file.createdAt);
	$: subtitle = !file
		? "Broken reference" // TODO: I18N
		: file.notes === null || !file.notes
		? timestamp
		: `${file.notes} - ${timestamp}`;

	let isModalOpen = false;

	function presentImageModal(event: Event) {
		event.preventDefault();
		dispatch("click", event);
		isModalOpen = true;
	}

	function closeModal() {
		isModalOpen = false;
	}

	function askToDelete(file: CustomEvent<Attachment>) {
		dispatch("delete", file.detail);
	}

	function askToDeleteReference() {
		dispatch("delete-reference", fileId);
	}
</script>

<ListItem {title} {subtitle} to="" on:click={presentImageModal} />
<Modal open={isModalOpen && !!file} {closeModal}>
	<FileView {file} on:delete={askToDelete} on:deleteReference={askToDeleteReference} />
</Modal>
