// src/pages/attachments/FileView.svelte
<script lang="ts">
	import type { Attachment } from "../../model/Attachment";
	import { createEventDispatcher } from "svelte";
	import { toTimestamp } from "../../transformers";
	import { useAttachmentsStore, useTransactionsStore } from "../../store";
	import ActionButton from "../../components/buttons/ActionButton.svelte";
	import DownloadButton from "../../components/buttons/DownloadButton.svelte";
	import ErrorNotice from "../../components/ErrorNotice.svelte";
	import List from "../../components/List.svelte";
	import TransactionListItem from "../transactions/TransactionListItem.svelte";
	import TrashIcon from "../../icons/Trash.svelte";

	export let file: Attachment | null = null;

	const dispatch = createEventDispatcher<{
		delete: Attachment;
		"delete-reference": void;
	}>();

	const attachments = useAttachmentsStore();
	const transactions = useTransactionsStore();

	let imageUrl: string | null = null;
	let imageLoadError: Error | null = null;
	$: linkedTransactions = transactions.allTransactions.filter(
		t => file !== null && t.attachmentIds.includes(file?.id)
	);
	$: transactionCount = linkedTransactions.length;
	$: timestamp = !file ? "now" : toTimestamp(file.createdAt);

	async function loadNewData(file: Attachment) {
		try {
			imageUrl = await attachments.imageDataFromFile(file);
		} catch (error) {
			imageLoadError = error as Error;
		}
	}

	$: {
		// Forget old value
		imageUrl = null;
		imageLoadError = null;

		if (file) void loadNewData(file);
	}

	function askToDelete(event: Event) {
		event.preventDefault();
		if (file) {
			dispatch("delete", file); // get rid of the file
		} else {
			dispatch("delete-reference"); // get rid of the file reference
		}
	}
</script>

<!-- TODO: I18N -->

<div class="main">
	{#if !file}
		<p>This file does not exist. Sorry.</p>
	{:else if imageLoadError}
		<ErrorNotice error={imageLoadError} />
	{:else if !imageUrl}
		<p>Loading...</p>
	{:else}
		<img src={imageUrl} alt="Stored file" />
	{/if}
</div>

<div>
	{#if file}
		<p>Name: <strong>{file.title}</strong></p>
		<p>Type: <strong>{file.type}</strong></p>
		<p>Timestamp: <strong>{timestamp}</strong></p>
	{/if}
</div>

{#if transactionCount > 0}
	<div>
		<h3>Linked Transaction{transactionCount !== 1 ? "s" : ""}</h3>
		<List class="files">
			{#each linkedTransactions as transaction (transaction.id)}
				<li>
					<TransactionListItem {transaction} />
				</li>
			{/each}
		</List>
	</div>
{/if}

<h3>Actions</h3>
<div class="buttons">
	{#if file}
		<DownloadButton class="download" {file} />
	{/if}

	{#if file}
		<ActionButton class="delete" kind="bordered-destructive" on:click={askToDelete}>
			<TrashIcon /> Delete</ActionButton
		>
	{:else}
		<ActionButton class="delete" kind="bordered" on:click={askToDelete}>
			<TrashIcon /> Remove this dead reference</ActionButton
		>
	{/if}
</div>

<style type="text/scss">
	.main {
		display: flex;
		flex-flow: row nowrap;
		align-items: center;
		justify-content: center;
		margin-bottom: 1em;

		img {
			max-width: 100%;
		}
	}

	.files {
		> li {
			overflow: hidden;
			border-radius: 4pt;
		}
	}

	.buttons {
		display: flex;
		flex-flow: row nowrap;

		> button {
			margin-top: 0;
		}

		> .download {
			margin-right: 8pt;
		}

		> .delete {
			margin-left: auto;

			.icon {
				margin-right: 6pt;
			}
		}
	}
</style>

// src/pages/attachments/FileView.vue
<script setup lang="ts">
import type { Attachment } from "../../model/Attachment";
import type { PropType } from "vue";
import ActionButton from "../../components/buttons/ActionButton.vue";
import DownloadButton from "../../components/buttons/DownloadButton.vue";
import ErrorNotice from "../../components/ErrorNotice.vue";
import List from "../../components/List.vue";
import TransactionListItem from "../transactions/TransactionListItem.vue";
import TrashIcon from "../../icons/Trash.vue";
import { ref, computed, watch, toRefs } from "vue";
import { toTimestamp } from "../../transformers";
import { useAttachmentsStore, useTransactionsStore } from "../../store";

const props = defineProps({
	file: { type: Object as PropType<Attachment | null>, default: null },
});
const { file } = toRefs(props);

const emit = defineEmits(["delete", "delete-reference"]);

const attachments = useAttachmentsStore();
const transactions = useTransactionsStore();

const imageUrl = ref<string | null>(null);
const imageLoadError = ref<Error | null>(null);
const linkedTransactions = computed(() =>
	transactions.allTransactions.filter(
		t => file.value !== null && t.attachmentIds.includes(file.value?.id)
	)
);
const transactionCount = computed(() => linkedTransactions.value.length);
const timestamp = computed(() => {
	if (!file.value) return "now";
	return toTimestamp(file.value.createdAt);
});

watch(
	file,
	async file => {
		// Forget old value
		imageUrl.value = null;
		imageLoadError.value = null;

		// Load new data
		if (file) {
			try {
				imageUrl.value = await attachments.imageDataFromFile(file);
			} catch (error) {
				imageLoadError.value = error as Error;
			}
		}
	},
	{ immediate: true }
);

function askToDelete() {
	if (file.value) {
		emit("delete", file.value); // get rid of the file
	} else {
		emit("delete-reference"); // get rid of the file reference
	}
}
</script>

<template>
	<div class="main">
		<!-- TODO: I18N -->
		<p v-if="!file">This file does not exist. Sorry.</p>
		<ErrorNotice v-else-if="imageLoadError" :error="imageLoadError" />
		<p v-else-if="!imageUrl">Loading...</p>
		<img v-else :src="imageUrl" />
	</div>

	<div>
		<p v-if="file"
			>Name: <strong>{{ file.title }}</strong></p
		>
		<p v-if="file"
			>Type: <strong>{{ file.type }}</strong></p
		>
		<p v-if="file"
			>Timestamp: <strong>{{ timestamp }}</strong></p
		>
	</div>

	<div v-if="transactionCount > 0">
		<h3>Linked Transaction{{ transactionCount !== 1 ? "s" : "" }}</h3>
		<List class="files">
			<li v-for="transaction in linkedTransactions" :key="transaction.id">
				<TransactionListItem :transaction="transaction" />
			</li>
		</List>
	</div>

	<h3>Actions</h3>
	<div class="buttons">
		<DownloadButton v-if="file" class="download" :file="file" />

		<ActionButton
			v-if="file"
			class="delete"
			kind="bordered-destructive"
			@click.prevent="askToDelete"
		>
			<TrashIcon /> Delete</ActionButton
		>
		<ActionButton v-else class="delete" kind="bordered" @click.prevent="askToDelete">
			<TrashIcon /> Remove this dead reference</ActionButton
		>
	</div>
</template>

<style scoped lang="scss">
.main {
	display: flex;
	flex-flow: row nowrap;
	align-items: center;
	justify-content: center;
	margin-bottom: 1em;

	img {
		max-width: 100%;
	}
}

.files {
	> li {
		overflow: hidden;
		border-radius: 4pt;
	}
}

.buttons {
	display: flex;
	flex-flow: row nowrap;

	> button {
		margin-top: 0;
	}

	> .download {
		margin-right: 8pt;
	}

	> .delete {
		margin-left: auto;

		.icon {
			margin-right: 6pt;
		}
	}
}
</style>
