// src/components/attachments/FileReattach.vue
<script setup lang="ts">
import type { Attachment } from "../../model/Attachment";
import type { Transaction } from "../../model/Transaction";
import type { PropType } from "vue";
import FileInput from "./FileInput.vue";
import FileListItem from "./FileListItem.vue";
import List from "../List.vue";
import ListItem from "../ListItem.vue";
import { useAttachmentsStore, useTransactionsStore, useUiStore } from "../../store";
import { computed, toRefs } from "vue";

const emit = defineEmits(["close"]);

const props = defineProps({
	transaction: { type: Object as PropType<Transaction>, required: true },
	fileId: { type: String, required: true },
});
const { transaction, fileId } = toRefs(props);

const attachments = useAttachmentsStore();
const transactions = useTransactionsStore();
const ui = useUiStore();

const files = computed(() => attachments.allAttachments);
const numberOfFiles = computed(() => files.value.length);

async function selectNewFile(attachment: Attachment) {
	const newTransaction = transaction.value.copy();
	newTransaction.addAttachmentId(attachment.id);
	newTransaction.removeAttachmentId(fileId.value);
	await transactions.updateTransaction(newTransaction);
	emit("close");
}

async function createNewFile(file: File | null): Promise<void> {
	if (!file) return;

	try {
		const attachment = await attachments.createAttachmentFromFile(file);
		await selectNewFile(attachment);
	} catch (error: unknown) {
		ui.handleError(error);
	}
}
</script>

<template>
	<div>
		<h3>Fix broken reference</h3>
		<p
			>This attachment somehow got lost in the mix, possibly due to an import bug. Select the
			correct file below:</p
		>

		<List>
			<li>
				<FileInput @input="createNewFile">
					<template #default="{ click }">
						<ListItem title="Upload a file" to="" @click.prevent="click" />
					</template>
				</FileInput>
			</li>
			<li v-for="file in files" :key="file.id">
				<FileListItem :file-id="file.id" @click.prevent="() => selectNewFile(file)" />
			</li>
			<li v-if="numberOfFiles > 0">
				<p class="footer">{{ numberOfFiles }} file<span v-if="numberOfFiles !== 1">s</span></p>
			</li>
		</List>
	</div>
</template>

// src/pages/attachments/FileReattach.svelte
<script lang="ts">
	import type { Attachment } from "../../model/Attachment";
	import type { Transaction } from "../../model/Transaction";
	import { createEventDispatcher } from "svelte";
	import { useAttachmentsStore, useTransactionsStore, useUiStore } from "../../store";
	import FileInput from "./FileInput.svelte";
	import FileListItem from "./FileListItem.svelte";
	import List from "../../components/List.svelte";
	import ListItem from "../../components/ListItem.svelte";
	import {
		addAttachmentToTransaction,
		transaction as copy,
		removeAttachmentIdFromTransaction,
	} from "../../model/Transaction";

	const dispatch = createEventDispatcher<{
		close: void;
	}>();

	export let transaction: Transaction;
	export let fileId: string;

	const attachments = useAttachmentsStore();
	const transactions = useTransactionsStore();
	const ui = useUiStore();

	$: files = attachments.allAttachments;
	$: numberOfFiles = files.length;

	async function selectNewFile(attachment: Attachment) {
		const newTransaction = copy(transaction);
		addAttachmentToTransaction(newTransaction, attachment);
		removeAttachmentIdFromTransaction(newTransaction, fileId);
		await transactions.updateTransaction(newTransaction);
		dispatch("close");
	}

	async function createNewFile(event: CustomEvent<File | null>): Promise<void> {
		const file = event.detail;
		if (!file) return;

		try {
			const attachment = await attachments.createAttachmentFromFile(file);
			await selectNewFile(attachment);
		} catch (error) {
			ui.handleError(error);
		}
	}
</script>

<div>
	<!-- TODO: I18N -->
	<h3>Fix broken reference</h3>
	<p
		>This attachment somehow got lost in the mix, possibly due to an import bug. Select the correct
		file below:</p
	>

	<List>
		<li>
			<FileInput on:input={createNewFile} let:click>
				<ListItem
					title="Upload a file"
					to=""
					on:click={e => {
						e.preventDefault();
						click();
					}}
				/>
			</FileInput>
		</li>
		{#each files as file (file.id)}
			<li>
				<FileListItem
					fileId={file.id}
					on:click={e => {
						e.preventDefault();
						selectNewFile(file);
					}}
				/>
			</li>
		{/each}
		{#if numberOfFiles > 0}
			<li>
				<p class="footer"
					>{numberOfFiles} file{#if numberOfFiles !== 1}s{/if}</p
				>
			</li>
		{/if}
	</List>
</div>
