// src/pages/transactions/TransactionCreateModal.svelte
<script lang="ts">
	import type { Account } from "../../model/Account";
	import Modal from "../../components/Modal.svelte";
	import TransactionEdit from "../transactions/TransactionEdit.svelte";

	export let account: Account;
	export let isOpen: boolean;
	export let closeModal: () => void;
</script>

<Modal open={isOpen} {closeModal}>
	<TransactionEdit {account} on:finished={closeModal} />
</Modal>

// components/transactions/TransactionCreateModal.vue
<script setup lang="ts">
import type { PropType } from "vue";
import type { Account } from "../../model/Account";
import Modal from "../../components/Modal.vue";
import TransactionEdit from "../transactions/TransactionEdit.vue";

defineProps({
	account: { type: Object as PropType<Account>, required: true },
	isOpen: { type: Boolean, required: true },
	closeModal: { type: Function as PropType<() => void>, required: true },
});
</script>

<template>
	<Modal :open="isOpen" :close-modal="closeModal">
		<TransactionEdit :account="account" @finished="closeModal" />
	</Modal>
</template>
