// src/components/AppVersion.vue
<script setup lang="ts">
import { useUiStore } from "../store";
import { computed, onMounted } from "vue";
import { version as _clientVersion } from "../version";
import OutLink from "./OutLink.vue";

const ui = useUiStore();

const serverVersion = computed(() => ui.serverVersion);
const loadingError = computed(() => ui.serverLoadingError);
const isLoading = computed(
	() => serverVersion.value === "loading" || typeof serverVersion.value !== "string"
);

onMounted(() => {
	void ui.loadServerVersion();
});

const clientVersion = computed(() => _clientVersion);
const repositoryUrl = computed(
	() => `https://github.com/AverageHelper/accountable-vue/tree/v${clientVersion.value}`
);
</script>

<template>
	<OutLink :to="repositoryUrl"
		>{{ $t("common.accountable") }} {{ $t("common.client") }} v{{ clientVersion }},
		{{ $t("common.server") }}
		<template v-if="isLoading">
			<span :title="loadingError?.message">vX.X.X</span>
		</template>
		<template v-else>v{{ serverVersion }}</template>
	</OutLink>
</template>

// src/components/AppVersion.svelte
<script lang="ts">
	import { _ } from "svelte-i18n";
	import { useUiStore } from "../store";
	import { version as clientVersion } from "../version";
	import OutLink from "./OutLink.svelte";

	const ui = useUiStore();

	$: serverVersion = ui.serverVersion;
	$: loadingError = ui.serverLoadingError;
	$: isLoading = serverVersion === "loading" || typeof serverVersion !== "string";

	void ui.loadServerVersion();

	const repositoryUrl = `https://github.com/AverageHelper/accountable-vue/tree/v${clientVersion}`;
</script>

<OutLink to={repositoryUrl} class={$$props.class}
	>{$_("common.accountable")}
	{$_("common.client")} v{clientVersion},
	{$_("common.server")}
	{#if isLoading}
		<span title={loadingError?.message}>vX.X.X</span>
	{:else}
		v{serverVersion}
	{/if}
</OutLink>
