// src/components/buttons/EditButton.svelte
<script lang="ts">
	import ActionButton from "./ActionButton.svelte";
	import EditIcon from "../../icons/Edit.svelte";
	import Modal from "../Modal.svelte";

	export let disabled: boolean = false;

	let isOpen = false;

	function closeModal() {
		isOpen = false;
	}

	function toggle() {
		isOpen = !isOpen;
	}
</script>

<ActionButton {disabled} on:click={toggle}>
	<slot name="icon">
		<EditIcon class="icon" />
	</slot>
</ActionButton>

<Modal open={isOpen} {closeModal}>
	<slot name="modal" onFinished={closeModal} />
</Modal>

<style type="text/scss">
	.icon {
		position: relative;
		top: -2pt;
		width: 20pt;
		height: 20pt;
	}
</style>

// src/components/EditButton.vue
<script setup lang="ts">
import ActionButton from "./ActionButton.vue";
import EditIcon from "../icons/Edit.vue";
import Modal from "./Modal.vue";
import { ref } from "vue";

const isOpen = ref(false);

function closeModal() {
	isOpen.value = false;
}
</script>

<template>
	<ActionButton @click="isOpen = !isOpen">
		<EditIcon class="icon" />
	</ActionButton>

	<Modal :open="isOpen" :close-modal="closeModal">
		<slot name="modal" />
	</Modal>
</template>

<style scoped lang="scss">
.icon {
	position: relative;
	top: -2pt;
	width: 20pt;
	height: 20pt;
}
</style>
