// src/pages/tags/TagList.svelte
<script lang="ts">
	import type { Tag as TagObject, TagRecordParams } from "../../model/Tag";
	import { createEventDispatcher, tick } from "svelte";
	import { tag as newTag } from "../../model/Tag";
	import { useTagsStore } from "../../store";
	import Modal from "../../components/Modal.svelte";
	import Tag from "./Tag.svelte";
	import TagEdit from "./TagEdit.svelte";

	const dispatch = createEventDispatcher<{
		"create-tag": TagRecordParams;
		"modify-tag": TagObject;
		"remove-tag": TagObject;
	}>();

	export let tagIds: Array<string>;

	let tagEdit: TagEdit | undefined;
	let isCreatingTag = false;
	let tagToEdit: TagObject | null = null;
	$: isEditingTag = tagToEdit !== null;
	$: isModalOpen = isCreatingTag || isEditingTag;

	const tags = useTagsStore();

	$: referencedTags = tags.allTags
		.filter(tag => tagIds.includes(tag.id))
		.sort((a, b) => a.name.localeCompare(b.name));

	async function addTag() {
		isCreatingTag = true;
		await tick(); // wait to focus until the element is attached
		tagEdit?.focus();
	}

	function removeTag(tag: TagObject) {
		dispatch("remove-tag", tag);
	}

	function closeModal() {
		isCreatingTag = false;
		tagToEdit = null;
	}

	function commitTag(params: CustomEvent<TagRecordParams | null>) {
		if (params.detail === null) {
			// nop
		} else if (isCreatingTag) {
			dispatch("create-tag", params.detail);
		} else if (tagToEdit) {
			const updatedTag = newTag({ ...tagToEdit, ...params.detail });
			dispatch("modify-tag", updatedTag);
		}
		closeModal();
	}

	function useTag(tag: CustomEvent<TagObject>) {
		dispatch("create-tag", tag.detail); // The parent worries about preventing duplicates
		closeModal();
	}
</script>

<div class="tag-list">
	<ul class="tags">
		{#each referencedTags as tag (tag.id)}
			<li>
				<Tag {tag} onRemove={removeTag} />
			</li>
		{/each}
		<li>
			<!-- TODO: I18N -->
			<a href="#" on:click|preventDefault={addTag}>Add tag</a>
		</li>
	</ul>
</div>

<Modal open={isModalOpen} {closeModal}>
	<TagEdit bind:this={tagEdit} on:selected={useTag} on:finished={commitTag} />
</Modal>

<style type="text/scss">
	@use "styles/colors" as *;

	.tag-list {
		display: flex;
		flex-flow: row wrap;
		align-items: baseline;

		ul.tags {
			display: flex;
			flex-flow: row wrap;
			list-style: none;
			padding: 0;
			max-width: 36em;
			margin: 0;
		}

		a {
			white-space: nowrap;
		}
	}
</style>

// src/components/TagList.vue
<script setup lang="ts">
import type { PropType } from "vue";
import type { TagRecordParams } from "../model/Tag";
import Modal from "./Modal.vue";
import Tag from "./Tag.vue";
import TagEdit from "./TagEdit.vue";
import { ref, computed, toRefs, nextTick } from "vue";
import { Tag as TagObject } from "../model/Tag";
import { useTagsStore } from "../store";

const emit = defineEmits(["create-tag", "modify-tag", "remove-tag"]);

const props = defineProps({
	tagIds: { type: Array as PropType<ReadonlyArray<string>>, required: true },
});
const { tagIds } = toRefs(props);

const tags = useTagsStore();
const theseTags = computed(() =>
	(tagIds.value ?? []).map(id => tags.items[id] ?? new TagObject(id, { name: id, colorId: "red" }))
);

const tagEdit = ref<{ focus: () => void } | null>(null);
const isCreatingTag = ref(false);
const tagToEdit = ref<TagObject | null>(null);
const isEditingTag = computed(() => tagToEdit.value !== null);
const isModalOpen = computed(() => isCreatingTag.value || isEditingTag.value);

async function addTag() {
	isCreatingTag.value = true;
	await nextTick(); // wait to focus until the element is attached
	tagEdit.value?.focus();
}

function removeTag(tag: TagObject) {
	emit("remove-tag", tag);
}

function closeModal() {
	isCreatingTag.value = false;
	tagToEdit.value = null;
}

function commitTag(params: TagRecordParams | null) {
	if (params === null) {
		// nop
	} else if (isCreatingTag.value) {
		emit("create-tag", params);
	} else if (tagToEdit.value) {
		const updatedTag = tagToEdit.value.updatedWith(params);
		emit("modify-tag", updatedTag);
	}
	closeModal();
}
</script>

<template>
	<div class="tag-list">
		<ul v-if="theseTags.length > 0" class="tags">
			<li v-for="tag in theseTags" :key="tag.id">
				<Tag :tag="tag" :on-remove="() => removeTag(tag)" />
			</li>
		</ul>
		<p v-else class="empty">No tags</p>

		<a href="#" @click.prevent="addTag">Add tag</a>
	</div>

	<Modal :open="isModalOpen" :close-modal="closeModal">
		<TagEdit ref="tagEdit" @finished="commitTag" />
	</Modal>
</template>

<style scoped lang="scss">
@use "styles/colors" as *;

.tag-list {
	display: flex;
	flex-flow: row nowrap;
	justify-content: space-between;
	align-items: baseline;

	ul.tags {
		display: flex;
		flex-flow: row wrap;
		list-style: none;
		padding: 0;
		max-width: 36em;
	}

	p.empty {
		color: color($secondary-label);
		text-align: left;
		margin-top: 0.5em;
		font-style: italic;
		font-weight: normal;
	}

	a {
		font-weight: bold;
		white-space: nowrap;
	}
}
</style>
