// src/pages/settings/Import.svelte
<script lang="ts">
	import type { DatabaseSchema } from "../../model/DatabaseSchema";
	import type { Entry } from "@zip.js/zip.js";
	import { accountsPath } from "../../router";
	import { BlobReader, TextWriter, ZipReader } from "@zip.js/zip.js";
	import { create } from "superstruct";
	import { schema } from "../../model/DatabaseSchema";
	import { toast } from "@zerodevx/svelte-toast";
	import { useUiStore } from "../../store";
	import { useRouter } from "vue-router";
	import FileInput from "../attachments/FileInput.svelte";
	import ActionButton from "../../components/buttons/ActionButton.svelte";
	import ImportProcessModal from "./ImportProcessModal.svelte";

	const ui = useUiStore();
	const router = useRouter();

	let isLoading = false;
	let archive: Array<Entry> | null = null;
	let dbName = "";
	let db: DatabaseSchema | null = null;

	async function onFileReceived(event: CustomEvent<File>) {
		const file = event.detail;
		archive = null;
		dbName = "";
		db = null;
		isLoading = true;

		let msg = `Loading ${file.name}`; // TODO: I18N
		const progressMeter = toast.push(msg, {
			duration: 300,
			initial: 0,
			next: 0,
			dismissable: false,
		});

		const reader = new ZipReader(new BlobReader(file));
		try {
			const zipFile = await reader.getEntries({
				onprogress: progress => {
					msg = `Loading ${file.name}: ${progress}%`; // TODO: I18N
					toast.set(progressMeter, { msg, next: progress });
				},
			});

			const dbFile = zipFile.find(f => f.filename === "accountable/database.json");
			if (!dbFile?.getData)
				throw new TypeError("accountable/database.json not present at root of zip"); // TODO: I18N

			const jsonString = (await dbFile.getData(new TextWriter())) as string;
			const json = JSON.parse(jsonString) as unknown;
			db = create(json, schema);
			dbName = file.name;
			archive = zipFile;
		} catch (error) {
			ui.handleError(error);
		} finally {
			toast.set(progressMeter, { next: 1 });
			await reader.close();
		}

		isLoading = false;
	}

	function forgetFile() {
		db = null;
		dbName = "";
		void router.push(accountsPath());
	}
</script>

<form on:submit|preventDefault>
	<!-- TODO: I18N -->
	<h3>Import</h3>
	<p>Import a JSON file describing one or more accounts.</p>
	<div class="buttons">
		<FileInput accept="application/zip" disabled={isLoading} on:input={onFileReceived} let:click>
			<ActionButton
				kind="bordered"
				disabled={isLoading}
				on:click={e => {
					e.preventDefault();
					click();
				}}>Import</ActionButton
			>
		</FileInput>
	</div>
</form>

<ImportProcessModal fileName={dbName} {db} zip={archive} on:finished={forgetFile} />

<style type="text/scss">
	p {
		margin-bottom: 0;
	}

	.buttons {
		display: flex;
		flex-flow: row wrap;

		:not(:last-child) {
			margin-right: 8pt;
		}

		* {
			text-decoration: none;
		}
	}
</style>

// src/client/components/settings/Import.vue
<script setup lang="ts">
import type { DatabaseSchema } from "../../model/DatabaseSchema";
import ActionButton from "../ActionButton.vue";
import FileInput from "../attachments/FileInput.vue";
import ImportProcessModal from "./ImportProcessModal.vue";
import JSZip from "jszip";
import { schema } from "../../model/DatabaseSchema";
import { ref } from "vue";
import { useUiStore } from "../../store";
import { useRouter } from "vue-router";

const ui = useUiStore();
const router = useRouter();

const isLoading = ref(false);
const zip = ref<JSZip | null>(null);
const dbName = ref("");
const db = ref<DatabaseSchema | null>(null);

// TODO: Move this into a store
async function onFileReceived(file: File) {
	zip.value = null;
	dbName.value = "";
	db.value = null;
	isLoading.value = true;

	try {
		const zipFile = await JSZip.loadAsync(file);
		const dbFile = zipFile.files["accountable/database.json"] ?? null;
		if (!dbFile) throw new TypeError("accountable/database.json not present at root of zip");

		const jsonString = await dbFile.async("string");
		const json = JSON.parse(jsonString) as unknown;
		db.value = (await schema.validateAsync(json)) as DatabaseSchema;
		dbName.value = file.name;
		zip.value = zipFile;
	} catch (error: unknown) {
		ui.handleError(error);
	}

	isLoading.value = false;
}

function forgetFile() {
	db.value = null;
	dbName.value = "";
	void router.push("/accounts");
}
</script>

<template>
	<form @submit.prevent>
		<h3>Import</h3>
		<p>Import a JSON file describing one or more accounts.</p>
		<div class="buttons">
			<FileInput accept="application/zip" :disabled="isLoading" @input="onFileReceived">
				<template #default="{ click }">
					<ActionButton kind="bordered" :disabled="isLoading" @click.prevent="click"
						>Import</ActionButton
					>
				</template>
			</FileInput>
		</div>
	</form>

	<ImportProcessModal :file-name="dbName" :db="db" :zip="zip" @finished="forgetFile" />
</template>

<style scoped lang="scss">
p {
	margin-bottom: 0;
}

.buttons {
	display: flex;
	flex-flow: row wrap;

	:not(:last-child) {
		margin-right: 8pt;
	}

	* {
		text-decoration: none;
	}
}
</style>
