// src/pages/locations/LocationView.vue
<script setup lang="ts">
import type { Location } from "../../model/Location";
import type { PropType } from "vue";

defineProps({
	location: { type: Object as PropType<Location>, required: true },
});
</script>

<template>
	<p>{{ location.title }}</p>
	<p>{{ location.subtitle }}</p>
	<p>{{ location.lastUsed }}</p>
	<p>{{ location.coordinate }}</p>
</template>

// src/pages/locations/LocationView.svelte
<script lang="ts">
	import type { Location } from "../../model/Location";

	export let location: Location;
</script>

<p>ID: {location.id}</p>
<p>Title: {location.title}</p>
<p>Subtitle: {location.subtitle}</p>
<p>Last Used: {location.lastUsed}</p>
{#if location.coordinate}
	<p>Lat: {location.coordinate.lat}</p>
	<p>Lng: {location.coordinate.lng}</p>
{/if}
