// src/pages/accounts/AccountListItem.svelte
<script lang="ts">
	import type { Account } from "../../model/Account";
	import { accountPath } from "../../router";
	import { intlFormat } from "../../transformers";
	import { isNegative as isDineroNegative } from "dinero.js";
	import { onMount } from "svelte";
	import { useAccountsStore, useTransactionsStore } from "../../store";
	import ListItem from "../../components/ListItem.svelte";

	export let account: Account;
	export let link: boolean = true;
	export let count: number | null = null;

	const accounts = useAccountsStore();
	const transactions = useTransactionsStore();

	$: accountRoute = link ? accountPath(account.id) : "#"; // TODO: I18N
	$: theseTransactions = transactions.transactionsForAccount[account.id];

	$: remainingBalance = accounts.currentBalance[account.id] ?? null;
	$: isBalanceNegative = remainingBalance !== null && isDineroNegative(remainingBalance);

	$: numberOfTransactions =
		theseTransactions === undefined
			? count ?? null
			: count ?? Object.keys(theseTransactions).length;

	$: notes = account.notes?.trim() ?? "";
	$: countString = `${numberOfTransactions ?? "?"} transaction${
		numberOfTransactions === 1 ? "" : "s"
	}`; // TODO: I18N
	$: subtitle = !notes
		? countString
		: numberOfTransactions === null
		? notes
		: `${countString} - ${notes}`;

	onMount(async () => {
		await transactions.getTransactionsForAccount(account);
	});
</script>

<ListItem
	to={accountRoute}
	title={account.title}
	{subtitle}
	count={remainingBalance ? intlFormat(remainingBalance) : "--"}
	negative={isBalanceNegative}
	class={$$props.class}
	on:click
/>

// src/client/components/accounts/AccountListItem.vue
<script setup lang="ts">
import type { Transaction } from "../../model/Transaction";
import ListItem from "../ListItem.vue";
import { Account } from "../../model/Account";
import { computed, toRefs, onMounted } from "vue";
import { useTransactionsStore } from "../../store";

const props = defineProps({
	account: { type: Account, required: true },
	link: { type: Boolean, default: true },
});
const { account, link } = toRefs(props);

const transactions = useTransactionsStore();
const accountRoute = computed(() => (link.value ? `/accounts/${account.value.id}` : "#"));
const theseTransactions = computed(
	() => transactions.transactionsForAccount[account.value.id] as Dictionary<Transaction> | undefined
);

const numberOfTransactions = computed<number | null>(() => {
	if (theseTransactions.value === undefined) {
		return null;
	}
	return Object.keys(theseTransactions.value).length;
});

onMounted(async () => {
	if (theseTransactions.value === undefined) {
		await transactions.getTransactionsForAccount(account.value);
	}
});
</script>

<template>
	<ListItem
		:to="accountRoute"
		:title="account.title"
		:subtitle="account.notes"
		:count="numberOfTransactions"
	/>
</template>
