// src/App.svelte
<script lang="ts">
	import type { SvelteToastOptions } from "@zerodevx/svelte-toast";
	import { onMount } from "svelte";
	import { SvelteToast } from "@zerodevx/svelte-toast";
	import { useUiStore } from "./store/uiStore";
	import Navbar from "./components/Navbar.svelte";

	const ui = useUiStore();

	const options: SvelteToastOptions = {};

	onMount(() => {
		ui.watchColorScheme();
	});
</script>

<Navbar />
<keep-alive>
	<router-view />
</keep-alive>
<div id="modal" />
<SvelteToast {options} />

<style type="text/scss">
	@use "styles/colors" as *;
	@import "styles/setup";

	:global(#app *) {
		box-sizing: border-box;
	}

	:global(html, body) {
		padding: 0;
		margin: 0;
	}

	:global(main.content) {
		margin: 0;
		padding: 16pt 24pt;
		overflow-y: scroll;
		overflow-x: hidden;
		height: calc(100vh - 44pt);

		.error {
			color: color($red);
		}
	}

	:global(a) {
		color: color($link);
	}

	// Toasts
	:global(.toast-success) {
		--toastBackground: color($alert-success);
		--toastBarBackground: color($green);
	}

	:global(.toast-error) {
		--toastBackground: color($alert-failure);
		--toastBarBackground: color($red);
	}
</style>

// src/client/App.vue
<script setup lang="ts">
import ErrorNotice from "./components/ErrorNotice.vue";
import Navbar from "./components/Navbar.vue";
import { bootstrap, isWrapperInstantiated } from "./transport";
import { computed, ref, onMounted } from "vue";
import { useRoute } from "vue-router";
import { useAuthStore } from "./store/authStore";
import { useUiStore } from "./store/uiStore";

const route = useRoute();
const auth = useAuthStore();
const ui = useUiStore();

const bootstrapError = ref<Error | null>(null);
const title = computed<string>(() => {
	const titleOrGetter = route.meta.title;
	if (titleOrGetter === undefined) {
		return "Home";
	}
	if (typeof titleOrGetter === "string") {
		return titleOrGetter;
	}
	return titleOrGetter();
});

onMounted(() => {
	ui.watchColorScheme();
	if (isWrapperInstantiated()) return;

	try {
		bootstrap();
		auth.watchAuthState();
	} catch (error: unknown) {
		if (error instanceof Error) {
			bootstrapError.value = error;
		} else {
			bootstrapError.value = new Error(JSON.stringify(error));
		}
	}
});
</script>

<template>
	<Navbar :title="title" />
	<main class="content">
		<ErrorNotice :error="bootstrapError" />
		<template v-if="!bootstrapError">
			<keep-alive>
				<router-view />
			</keep-alive>
			<!-- <router-view v-slot="{ Component }">
				<keep-alive>
					<component :is="Component" />
				</keep-alive>
			</router-view> -->
		</template>
	</main>
	<div id="modal" />
</template>

<style lang="scss">
@use "styles/colors" as *;
@import "styles/setup";

#app * {
	box-sizing: border-box;
}

html,
body {
	padding: 0;
	margin: 0;
}

main.content {
	margin: 1em;

	.error {
		color: color($red);
	}
}

a {
	color: color($link);
}
</style>
